// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"time"
)

type Exercise struct {
	ID                      int64
	Name                    string
	Description             sql.NullString
	Warning                 sql.NullString
	RecommendedRepsAmount   sql.NullInt16
	RecommendedRestDuration sql.NullInt32
	IsGymRequired           sql.NullBool
	VideoTutorialUrl        sql.NullString
	MachineID               sql.NullInt64
	MuscleGroupID           sql.NullInt64
	UpdatedAt               time.Time
	CreatedAt               time.Time
}

type ExercisesImage struct {
	ID         int64
	ExerciseID sql.NullInt64
	ImageUrl   string
	AltText    sql.NullString
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type Machine struct {
	ID          int64
	Name        string
	Description sql.NullString
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

type MachinesImage struct {
	ID        int64
	MachineID sql.NullInt64
	ImageUrl  string
	AltText   sql.NullString
	UpdatedAt time.Time
	CreatedAt time.Time
}

type MuscleGroup struct {
	ID   int64
	Name string
}
