// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID                      int64
	Name                    string
	Description             pgtype.Text
	Warning                 pgtype.Text
	RecommendedRepsAmount   pgtype.Int2
	RecommendedRestDuration pgtype.Int4
	IsGymRequired           pgtype.Bool
	VideoTutorialUrl        pgtype.Text
	MachineID               pgtype.Int8
	MuscleGroupID           pgtype.Int8
	UpdatedAt               time.Time
	CreatedAt               time.Time
}

type ExercisesImage struct {
	ID         int64
	ExerciseID pgtype.Int8
	ImageUrl   string
	AltText    pgtype.Text
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type Machine struct {
	ID          int64
	Name        string
	Description pgtype.Text
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

type MachinesImage struct {
	ID        int64
	MachineID pgtype.Int8
	ImageUrl  string
	AltText   pgtype.Text
	UpdatedAt time.Time
	CreatedAt time.Time
}

type MuscleGroup struct {
	ID   int64
	Name string
}
