// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: muscle.sql

package dbsqlc

import (
	"context"
)

const createMuscleGroup = `-- name: CreateMuscleGroup :one
INSERT INTO muscle_group (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateMuscleGroup(ctx context.Context, name string) (MuscleGroup, error) {
	row := q.db.QueryRow(ctx, createMuscleGroup, name)
	var i MuscleGroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteMuscleGroup = `-- name: DeleteMuscleGroup :exec
DELETE FROM muscle_group WHERE id = $1
`

func (q *Queries) DeleteMuscleGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMuscleGroup, id)
	return err
}

const getMuscleGroup = `-- name: GetMuscleGroup :one
SELECT id, name FROM muscle_group WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMuscleGroup(ctx context.Context, id int64) (MuscleGroup, error) {
	row := q.db.QueryRow(ctx, getMuscleGroup, id)
	var i MuscleGroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listMuscleGroup = `-- name: ListMuscleGroup :many
SELECT id, name FROM muscle_group
`

func (q *Queries) ListMuscleGroup(ctx context.Context) ([]MuscleGroup, error) {
	rows, err := q.db.Query(ctx, listMuscleGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MuscleGroup
	for rows.Next() {
		var i MuscleGroup
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMuscleGroup = `-- name: UpdateMuscleGroup :one
UPDATE muscle_group SET name = $2 WHERE id = $1 RETURNING id, name
`

type UpdateMuscleGroupParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateMuscleGroup(ctx context.Context, arg UpdateMuscleGroupParams) (MuscleGroup, error) {
	row := q.db.QueryRow(ctx, updateMuscleGroup, arg.ID, arg.Name)
	var i MuscleGroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
